import React from 'react';
import { Link } from 'react-router-dom';
import IdCode from '@/components/shared/IdCode';
import { PRECISION_LABEL } from '@/pages/Timeline';
import { CaseLinks, ResearchRecordList, chip } from '@/components/research/ResearchRecords';
import { cn } from '@/lib/utils';

// OVNIS page tabs for the reports workspace (TWIN-013/222/223) and the show log
// (TWIN-009/208..210/218/221). Both read OVNIS's exported records; a report is
// a deterministic restatement of one case with its receipt, and the show log
// lists only episodes a curator recorded with their primary source.

export function ReportsWorkspace() {
  return (
    <div className="space-y-3">
      <p className="text-xs text-muted-foreground">
        One report per case, generated by OVNIS from its ledgers. Each restates the case as recorded, lists what is unresolved and carries a reproducibility receipt.
      </p>
      <ResearchRecordList kind="reports" emptyText="This Hub holds no OVNIS case reports. Run the federation ingest to load the producer's export.">
        {(row) => {
          const report = row.attributes.report || {};
          const recorded = report.case || {};
          return (
            <div className="flex flex-wrap items-center justify-between gap-3" data-report-row={report.case_id}>
              <div className="space-y-1">
                <div className="flex flex-wrap items-center gap-2 text-xs">
                  <IdCode>{row.record_id}</IdCode>
                  {recorded.object_type ? <span className={cn(chip, 'border-border text-muted-foreground')}>{recorded.object_type}</span> : null}
                </div>
                <p className="text-sm">
                  {recorded.date_local || 'Undated'}{' '}
                  <span className="text-xs text-muted-foreground">({PRECISION_LABEL[recorded.temporal_precision] || 'undated'})</span>
                  {' · '}{recorded.municipality || recorded.location_name || 'Place not recorded'}
                </p>
                <p className="text-xs text-muted-foreground">
                  {(report.unresolved || []).length} unresolved item{(report.unresolved || []).length === 1 ? '' : 's'} ·
                  {' '}{(report.linked?.manifestation_candidates || []).length} duplicate candidate(s) ·
                  {' '}receipt <span className="font-mono">{String(report.receipt?.report_sha256 || '').slice(0, 12)}</span>
                </p>
              </div>
              <Link className="text-sm text-primary underline" to={`/research/case/${encodeURIComponent(report.case_id)}`}>
                Open report
              </Link>
            </div>
          );
        }}
      </ResearchRecordList>
    </div>
  );
}

export function ShowLog() {
  return (
    <ResearchRecordList
      kind="episodes"
      emptyText="No media episodes are recorded in the OVNIS research ledger yet. An episode appears here only after a curator records it with its primary source."
    >
      {(episode) => {
        const a = episode.attributes;
        const code = [a.season != null ? `S${a.season}` : null, a.episode != null ? `E${a.episode}` : null].filter(Boolean).join(' ');
        return (
          <div className="space-y-1" data-episode={episode.record_id}>
            <p className="text-xs text-muted-foreground">{a.series}{code ? ` · ${code}` : ''}{a.air_date ? ` · aired ${a.air_date}` : ''}</p>
            <p className="text-sm font-semibold text-foreground">{a.title}</p>
            <p className="text-xs">
              {/^https?:\/\//i.test(a.primary_source_url || '') ? (
                <a className="text-primary underline" href={a.primary_source_url} target="_blank" rel="noreferrer noopener">Primary source</a>
              ) : null}
            </p>
            <p className="text-xs">Cases: <CaseLinks caseIds={episode.case_ids} /></p>
          </div>
        );
      }}
    </ResearchRecordList>
  );
}
